dist: xenial
language: cpp
os: linux

addons:
  apt:
    packages:
      - qt515base
    sources:
      - sourceline: 'ppa:beineri/opt-qt-5.15.0-xenial'

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
