dist: focal
language: cpp
os: linux

branches:
  except:
    - /^ci-\d/

addons:
  apt:
    packages:
      - qt515base
      - mesa-common-dev
      - libglu1-mesa-dev
      - g++-7
    sources:
      - sourceline: 'ppa:beineri/opt-qt-5.15.0-focal'

before_script:
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCI_BUILD_ID=$TRAVIS_BUILD_NUMBER -DCI_COMMIT_HASH="$TRAVIS_COMMIT" -DCI_TAG="auto-amd64-linux"

script:
  - make
  - ls -ln ./bin/

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name $GHUB_LOGIN
  - git config --local user.email $GHUB_EMAIL
  - git tag -f auto-amd64-linux
  - git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${GHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push -f gh auto-amd64-linux
  - git remote remove gh

deploy:
  provider: releases
  api_key: $GHUB_TOKEN
  file_glob: true
  file: ./bin/*
  name: Autorelease for amd64/Linux ($TRAVIS_BUILD_NUMBER)
  skip_cleanup: true
  target_commitish: $TRAVIS_COMMIT
  on:
    branch: master
