dist: xenial
language: cpp
os: linux

branches:
  except:
    - /^ci-\d/

addons:
  apt:
    packages:
      - qt515base
      - mesa-common-dev
      - libglu1-mesa-dev
      - g++-7
    sources:
      - sourceline: 'ppa:beineri/opt-qt-5.15.0-xenial'
      - ubuntu-toolchain-r-test

before_script:
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -DCMAKE_BUILD_TYPE=Release \
             -DCI_BUILD_ID=$TRAVIS_BUILD_NUMBER \
             -DCI_COMMIT_HASH=$TRAVIS_COMMIT

script:
  - make

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name $GHUB_LOGIN
  - git config --local user.email $GHUB_EMAIL
  - export TRAVIS_TAG=ci-$TRAVIS_BUILD_NUMBER
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GHUB_TOKEN
  file_glob: true
  file: ./bin/*
  skip_cleanup: true
  on:
    branch: master
