language: cpp

matrix:
  include:
  - os: osx
    osx_image: xcode11.2
    before_install:
      - brew install qt5
      - brew link qt5 --force
  - os: linux
    compiler:
      - gcc
      - clang
    before_install:
      - sudo apt-get update -qq
      - sudo apt-get install build-essential qt5-default

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
