dist: xenial
language: cpp
os: linux

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential qt5-default

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
